// ignore_for_file: public_member_api_docs, sort_constructors_first
// Generated by https://quicktype.io

class NewsModel {
  String pubDate;
  String sectionName;
  String title;
  String type;

  String webUrl;

  NewsModel({
    required this.pubDate,
    required this.sectionName,
    required this.type,
    required this.title,
    required this.webUrl,
  });

  factory NewsModel.fromJson(Map<String, dynamic> news) {
    return NewsModel(
      pubDate: news['webPublicationDate'],
      sectionName: news['sectionName'],
      title: news['webTitle'],
      type: news['type'],
      webUrl: news['webUrl'],
    );
  }
}


// {
//         "id": "australia-news/live/2023/may/07/jim-chalmers-federal-budget-petroleum-resource-rent-tax-king-charles-coronation-reactions",
//         "type": "liveblog",
//         "sectionId": "australia-news",
//         "sectionName": "Australia news",
//         "webPublicationDate": "2023-05-07T01:09:39Z",
//         "webTitle": "Australia news live: Chalmers confirms energy rebates for millions, relief for all ages amid reports of broader jobseeker changes",
//         "webUrl": "https://www.theguardian.com/australia-news/live/2023/may/07/jim-chalmers-federal-budget-petroleum-resource-rent-tax-king-charles-coronation-reactions",
//         "apiUrl": "https://content.guardianapis.com/australia-news/live/2023/may/07/jim-chalmers-federal-budget-petroleum-resource-rent-tax-king-charles-coronation-reactions",
//         "isHosted": false,
//         "pillarId": "pillar/news",
//         "pillarName": "News"
//       },